spring:
  datasource:
    hikari:
      max-lifetime: 1765000
      maximum-pool-size: 15
  thymeleaf:
    cache: false
    prefix: classpath:/static/html/
  config:
    location: classpath:/application-pwd.properties
  cache:
    type: REDIS

datasource:
  login:
    jdbc-url: jdbc:mysql://rm-wz92xoj923k8s3v8do.mysql.rds.aliyuncs.com:3306/user-account?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
  linkhome:
    jdbc-url: jdbc:mysql://rm-wz92xoj923k8s3v8do.mysql.rds.aliyuncs.com:3306/link-home?useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver

logging:
  level:
    root: debug


mybatis:
  type-aliases-package: com.zcc.login.vo,com.zcc.login.model,com.zcc.login.dto

jwt:
  header: Authorization
  secret: emhhbmdjaGljaGVuZw==
  expiration: 604800
  route:
    authentication:
      path: auth
      refresh: refresh

management:
  security:
    enabled: false
server:
  port: 8080
